import type { Metadata } from "next";

import "./globals.css";
import { ReactNode } from "react";
import { Locale } from "@/i18n/config";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: {
  children: ReactNode;
  params: Promise<{ lang: Locale }>;
}) {
  const { lang } = await params;
  return (
    <html lang={lang}>
      <body
      >
        {children}
      </body>
    </html>
  );
}
