import type { Metadata } from "next";

import "./globals.css";
import { ReactNode, Suspense } from "react";
import { LocaleProvider } from "@/i18n/LocaleProvider";
import { Header } from "./ui/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: ReactNode;

}) {

  return (
    <html>
      <body
      >
        <LocaleProvider>
          <Suspense>
            <Header/>
            {children}
          </Suspense>
        </LocaleProvider>
      </body>
    </html>
  );
}
